name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: "1.20"
          
    - name: Set up dependencies
      run: sudo -E apt-add-repository -y 'ppa:ubuntu-toolchain-r' && sudo apt-get install libasound2-dev libglew-dev libgles2-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - uses: actions/checkout@v3

    - name: vendor
      run: go mod vendor

    - name: Build
      run: go build -v ./...


      
