name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        go-version: '1.20'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.4.0
      
