name: Lint

on:
  push:
    branches: [ "master", "10-fix-ci" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: "1.20"
          
    - name: Set up dependencies
      run: sudo -E apt-add-repository -y 'ppa:ubuntu-toolchain-r' && sudo apt-get install libasound2-dev libglew-dev libgles2-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
    - uses: actions/checkout@v3

    - name: vendor
      run: go mod vendor

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.1

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: make test


      
