name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: "1.20"

    - uses: actions/checkout@v3

    - name: vendor
      run: go mod vendor

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

      
